name: WSL

on: [push]

jobs:
  docker_build:
    runs-on: wsl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the Docker image from the Dockerfile
      - name: Build Docker image
        run: docker build -t ci-pipeline .

      # Run tests inside the Docker container and export it to results in same folder 
      - name: Run tests inside Docker container
        run: |
          docker run -v $(pwd)/features/reports:/app/features/reports ci-pipeline

  test:
    runs-on: wsl
    needs: docker_build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ github.sha }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 


      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          sudo apt-get --only-upgrade install google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave selenium webdriver-manager pytest pyhamcrest allure-behave allure-python-commons

      - name: Install Allure CLI manually
        run: |
          # Download Allure CLI
          wget https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.tgz
          # Extract the archive
          tar -zxvf allure-2.20.1.tgz
          # Move allure to /usr/bin
          sudo mv allure-2.20.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Create directories for Allure results and history
        run: |
          mkdir -p features/reports/allure-results/history


      - name: Run tests and generate Allure results
        run: |
          mkdir -p features/reports/allure-results
          behave -f allure_behave.formatter:AllureFormatter -o features/reports/allure-results || true
          
      - name: Merge previous Allure history
        run: |
          cp -R features/reports/allure-results/history/* features/reports/allure-results/ || echo "No previous history to merge"

      - name: Generate Allure Report
        run: |
          allure generate features/reports/allure-results -o features/allure-report 

      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: features/allure-report
          retention-days: 5

  deploy:
    runs-on: wsl
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure Report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-html-report
          path: features/allure-report

